# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Buyer_pb2 as Buyer__pb2


class BuyerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notification_Print = channel.unary_unary(
                '/buyer.Buyer/Notification_Print',
                request_serializer=Buyer__pb2.NotificationRequest.SerializeToString,
                response_deserializer=Buyer__pb2.NotificationResponse.FromString,
                )


class BuyerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Notification_Print(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notification_Print': grpc.unary_unary_rpc_method_handler(
                    servicer.Notification_Print,
                    request_deserializer=Buyer__pb2.NotificationRequest.FromString,
                    response_serializer=Buyer__pb2.NotificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buyer.Buyer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Buyer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Notification_Print(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/buyer.Buyer/Notification_Print',
            Buyer__pb2.NotificationRequest.SerializeToString,
            Buyer__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
